### ISSUE TITLE
Symantec quarantines the windows install file immediately

### ISSUE THREAD

**Issue by staylorx** [exercism/windows-installer#30]
My work computer immediately quarantined the windows installer 1.4 file.

Both historical and current reputation has this comment: "There is strong evidence that this file is untrustworthy."

**Comment by rpottsoh** [comment]
@staylorx I'm sorry to hear you are experiencing difficulties with the installer.  Since it was released in August it has been downloaded over 2800 times with zero reported incidences of trouble.  

Can you provide more detailed information from Symantec?  I have not had access to any Symantec products for several years now, I always found Norton to be a little "over protective".

I want to work with you to get through this issue.  You may need to "teach" or instruct Norton to allow the installer to pass if Norton cannot give to specific details about it finds wrong with the file.

**Comment by staylorx** [comment]
@rpottsoh It's really no issue for me. I can switch over to my non-work rig and try it there. 

I'm sure our Symantec is probably a little tight. 

Details are here:
![image](https://user-images.githubusercontent.com/246923/32993768-dc84d670-cd19-11e7-920a-41f908a26cdf.png)
