### ISSUE TITLE
[Windows 10 x64] Error while trying to install Exercism CLI

### ISSUE THREAD

**Issue by catalin560** [exercism/windows-installer#35]
The installer malfunctions right after I open it (with admin rights) and I can't do anything else beside closing it...
![err](https://user-images.githubusercontent.com/22744333/38541765-bdf99048-3ca8-11e8-88a0-e94d19737f33.jpg)
downloaded from https://github.com/exercism/windows-installer/releases/tag/v1.4.2

**Comment by rpottsoh** [comment]
@catalin560 I am sorry you are experiencing this error.  This is a strange one to say the least.  How many times have you tried running the installer?  So far I am not able to reproduce the error.  Likely, within the next 24 hours, I will make a pre-release available that will address this issue.  I am working from my Windows 7 system at the moment.  I don't want to release anything until I have had a chance to look at this issue further using my Windows 10 system.

**Comment by rpottsoh** [comment]
@catalin560, I have figured it out.  Your Locale settings in Windows is what has triggered the error.  A minor fix to the installer will allow it to compensate for the settings of your installation of Windows.  There is nothing wrong with what you are doing.  I didn't account for the fact that sometimes `,` is used as a decimal separator instead of as a thousands separator.  I can recreate the error you reported if I force the system's settings for decimal and thousands separator to be opposite of what I am accustomed.

I will release  a pre-release version sooner, rather than later.  I will provide a link to it here.  I would appreciate it if you would download, try it, and report back to me how it behaves for you.

**Comment by rpottsoh** [comment]
@catalin560 I have published a pre-release that I would like for your to test for me, if you are willing and able.  You will find it here:
https://github.com/rpottsoh/exercism-windows-installer/releases/tag/v1.4.2.1

**Comment by MarZ3r0** [comment]
Thanks, I had the same error but with this pre-release the error have been solved.

**Comment by rpottsoh** [comment]
Excellent!  I appreciate the feedback @MarZ3r0.  :+1:

**Comment by catalin560** [comment]
@rpottsoh Aha! This time it worked! Although I've already figured out how to manually install it thanks to the help of @NobbZ on gitter!

Thank you very much for your prompt response!
