### ISSUE TITLE
Testing: what has happened/what needs to happen?

### ISSUE THREAD

**Issue by gusseting** [exercism/windows-installer#5]
Would it be possible to show what testing has happened so far, and what needs to happen? 
It would be great to see this installer in the CLI install pages as a simple download: http://exercism.io/cli
In order to see it as a simple download, I'm wondering if it's possible to test for at least the top 3 most used windows operating systems (rated top to bottom according to user statistics:
Operating System + Statistics:

```
- 10                8,572(54.03%)
- 7                 5,510(34.73%)
- 8.1               1,448(9.13%)
- XP                174(1.10%)
- 8                 118(0.74%)
- Vista             40(0.25%)
```

What help do you need in order to make that testing happen?

**Comment by blueelvis** [comment]
Hi Kylie!

Sorry for the delay. Life got in the way :P

Regarding the testing, I have tested the installer on the following operating systems -
 - Windows 10 64 bit
 - Windows 8 64 bit
 - Windows 7 64 bit

The package ran flawlessly on the above mentioned operating systems. Since it ran fine on Windows 8, I am very sure that there shouldn't be any problem on running it on Windows 8.1 as well :)
