### ISSUE TITLE
dotnet test not working on windows 10 home

### ISSUE THREAD

**Issue by CRhushikesh** [exercism/windows-installer#55]
when I type the command 
dotnet test   --- for testing suggested for first exercise...  it displays following message on CMD

> 'dotnet' is not recognized as an internal or external command,

operable program or batch file.

> 
![dotnet_test_failed](https://user-images.githubusercontent.com/50285224/58148256-a86c4400-7c7b-11e9-8947-5afebc19c992.png)

**Comment by rpottsoh** [comment]
@CRhushikesh I think you have posted this to the wrong repo.  This is the Windows Installer repo.  The Windows Installer is a tool for installing the CLI onto a Windows based system.

Your issue seems more appropriate to one of the language tracks.  Which language track are you attempting to setup?  I can then point you to the right place to seek assistance.  [Gitter](https://gitter.im/exercism/support) is another excellent place to find help as well.

**Comment by rpottsoh** [comment]
Let me know if I can be of some assistance.  For now I am going to close this issue.
